# Generated by Django 5.1.6 on 2025-02-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
