# Generated by Django 5.1.6 on 2025-03-13 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('horario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='GuiaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría de Guía',
                'verbose_name_plural': 'Categorías de Guías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guia_images/', verbose_name='Imagen Representativa')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('code_file', models.FileField(blank=True, null=True, upload_to='guia_codes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Código de la Guía (.zip)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guiacategory', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Texto'), ('latex', 'LaTeX'), ('code', 'Código')], max_length=10, verbose_name='Tipo de Bloque')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.guia')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GuiaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Valoración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guia_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_guia_comments', to=settings.AUTH_USER_MODEL)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.guia', verbose_name='Guía')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_guia_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.guiacomment')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Básico', 'Básico'), ('Premium', 'Premium'), ('Anual', 'Anual')], default='Básico', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
