# Generated by Django 5.1.6 on 2025-03-15 16:53

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.GridFSStorage(), upload_to='tutorial_images/', verbose_name='Imagen Representativa'),
        ),
    ]
