# Generated by Django 5.1.6 on 2025-03-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='code_file',
        ),
    ]
