# Generated by Django 5.1.6 on 2025-03-15 17:02

import core.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tutorial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='code_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.GridFSStorage(), upload_to='guia_codes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Código de la Guía (.zip)'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.GridFSStorage(), upload_to='guia_images/', verbose_name='Imagen Representativa'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.GridFSStorage(), upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio',
            field=models.FileField(storage=core.storage.GridFSStorage(), upload_to='podcast_audio/', verbose_name='Archivo de Audio'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=core.storage.GridFSStorage(), upload_to='podcast_covers/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='code_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.GridFSStorage(), upload_to='tutorial_codes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Código del Tutorial (.zip)'),
        ),
    ]
