# Generated by Django 5.1.6 on 2025-03-06 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tutorial_code_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='tutorial_codes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Código del Tutorial (.zip)'),
        ),
    ]
