# Generated by Django 5.1.6 on 2025-02-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tutorial_tutorialblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
