# Generated by Django 5.1.6 on 2025-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tutorial_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutorial_images/', verbose_name='Imagen Representativa'),
        ),
    ]
