# Generated by Django 4.2.19 on 2025-04-26 17:12

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tutorialcarouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiablock',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.GridFSStorage(), upload_to='guia_blocks/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='guiablock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Texto'), ('latex', 'LaTeX'), ('code', 'Código'), ('image', 'Imagen')], max_length=10, verbose_name='Tipo de Bloque'),
        ),
    ]
