# Generated by Django 4.2.19 on 2025-04-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_guiablock_image_alter_guiablock_block_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiablock',
            name='image',
        ),
        migrations.AlterField(
            model_name='guiablock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Texto'), ('latex', 'LaTeX'), ('code', 'Código')], max_length=10, verbose_name='Tipo de Bloque'),
        ),
    ]
