# Generated by Django 5.1.6 on 2025-03-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_tutorial_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría tutorial', 'verbose_name_plural': 'Categorías tutoriales'},
        ),
    ]
