# Generated by Django 5.1.6 on 2025-03-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contacto_correo_alter_contacto_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría de Guía',
                'verbose_name_plural': 'Categorías de Guías',
                'ordering': ['name'],
            },
        ),
    ]
