# Generated by Django 5.1.6 on 2025-03-11 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_guiacategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guia_images/', verbose_name='Imagen Representativa')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guiacategory', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Texto'), ('latex', 'LaTeX'), ('code', 'Código')], max_length=10, verbose_name='Tipo de Bloque')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.guia')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
