# Generated by Django 4.2.19 on 2025-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tutorial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Texto que aparece en Google (aprox. 150-160 caracteres).', max_length=165, null=True, verbose_name='Meta Descripción (para SEO)'),
        ),
    ]
