# Generated by Django 4.2.19 on 2025-06-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tutorial_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Texto que aparece en Google (aprox. 150-160 caracteres).', max_length=165, null=True, verbose_name='Meta Descripción (para SEO)'),
        ),
    ]
