# Generated by Django 5.1.6 on 2025-03-12 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_guiacomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='guia_codes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Código de la Guía (.zip)'),
        ),
    ]
