# Generated by Django 4.2.19 on 2025-07-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_guia_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiablock',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenido o Pie de Foto'),
        ),
    ]
