# Generated by Django 5.1.6 on 2025-03-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
