# Generated by Django 5.1.6 on 2025-03-04 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_comment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('audio', models.FileField(upload_to='podcast_audio/', verbose_name='Archivo de Audio')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='podcast_covers/', verbose_name='Portada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
