# Generated by Django 5.1.6 on 2025-03-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Categoría'),
        ),
    ]
