# Generated by Django 5.1.6 on 2025-03-05 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_podcastcategory_alter_podcast_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Valoración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_podcast_comments', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_podcast_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.podcastcomment')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.podcast', verbose_name='Podcast')),
            ],
        ),
    ]
